adviser/templatetags/urls.py
# -*- coding: utf-8 -*-
from typing import Optional, Any, Dict

from django import urls, template

from adviser.models import GeneralFields

register = template.Library()


@register.simple_tag(takes_context=True)
def translate_url(context: Dict[str, Any], language: Optional[str]) -> str:
    """Get the absolute URL of the current page for the specified language.

    Usage:
        {% translate_url 'en' %}
    """
    url = context['request'].build_absolute_uri()
    return urls.translate_url(url, language)


@register.simple_tag()
def get_extra_fields():
    return GeneralFields.objects.first()

api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from api.views import CreateCurrencyReportView

urlpatterns = [

    url(r'^cryptocurrency/$', CreateCurrencyReportView.as_view(), name='currency'),

    ]

exrates_adviser/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import include, reverse
from django.utils.translation import activate

from adviser.views import (AboutUsPageView, AdviserDemoPageView, AdviserFormView, AdviserProfileView,
                           AdviserUpdateProfileView, AdvisorProfileView, BecomeAdviserPageView, ChatPageView,
                           ClientCenterPageView,
                           DealPageView, FiatPageView, PrivacyPolicyPageView, SupportPageView)#, TermsPageView)
from analytics.views import ArticlePageView, ArticlesListPageView, ListArticleView

activate('en')

from django.conf import settings
from django.contrib import messages

import requests


def check_recaptcha(function):
    def wrap(request, *args, **kwargs):
        request.recaptcha_is_valid = None
        if request.method == 'POST':
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
                }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            if result['success']:
                request.recaptcha_is_valid = True
            else:
                request.recaptcha_is_valid = False
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
        return function(request, *args, **kwargs)

    wrap.__doc__ = function.__doc__
    wrap.__name__ = function.__name__
    return wrap


def home(request):
    return redirect(reverse("about-us"))


def page_not_found_view(request):
    return render(request, '404.html', {})


urlpatterns = i18n_patterns(
        url(r'^$', home, name='home'),
        url(r'^analytics-detail/(?P<slug>[-\w]+)/$', ArticlePageView.as_view(), name='analytics-detail'),
        url(r'^form-listing/$', check_recaptcha(DealPageView.as_view()), name='deal'),
        url(r'^advisor-demo/$', check_recaptcha(AdviserDemoPageView.as_view()), name='adviser-demo'),

        url(r'^(?P<type>[-\w]+)-profile/(?P<slug>[-\w]+)/$', AdvisorProfileView.as_view(), name='advisor-profile'),

        url(r'^(?P<type>[-\w]+)/(?P<slug>[-\w]+)/update/$', check_recaptcha(AdviserUpdateProfileView.as_view()),
            name='adviser-update'),
        url(r'^(?P<type>[-\w]+)/(?P<slug>[-\w]+)/$', check_recaptcha(AdviserProfileView.as_view()), name='adviser-detail'),

        url(r'^fiat/$', FiatPageView.as_view(), name='fiat'),
        url(r'^client-center/$', ClientCenterPageView.as_view(), name='client-center'),
        url(r'^privacy-policy/$', PrivacyPolicyPageView.as_view(), name='privacy-policy'),
        # url(r'^terms-of-use/$', TermsPageView.as_view(), name='terms-of-use'),

        url(r'^become-ambassador/$', BecomeAdviserPageView.as_view(), name='become-advisor'),
        url(r'^about-us/$', check_recaptcha(AboutUsPageView.as_view()), name='about-us'),

        url(r'^ambassador-form/$', AdviserFormView.as_view(), name='advisor-form'),
        url(r'^support-center/$', check_recaptcha(SupportPageView.as_view()), name='support-center'),

        url(r'^chat/$', ChatPageView.as_view(), name='chat'),
        url(r'^analytics/$', ArticlesListPageView.as_view(), name='analytics-list'),



        ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls = [url('admin/', admin.site.urls),
url(r'^api/articles/$', ListArticleView.as_view(), name='articles-list1'),
        url('i18n/', include('django.conf.urls.i18n')),
        url(r'^ckeditor/', include('ckeditor_uploader.urls')),
        url(r'^api/', include('api.urls')),
        ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += urls

adviser/models.py
# -*- coding: utf-8 -*-
import uuid

from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField

ADVISER_TYPE_ENUM = (
    (1, 'Company'),
    (2, 'Ambassador'),
    (3, 'Sales'),
    (4, 'Advisor')
    )


class Manager(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    job_title = models.CharField(max_length=255)
    telegram = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    avatar = models.ImageField(upload_to='images', default='images/default-ava.png')

    def __str__(self):
        return '{}, {}'.format(self.surname, self.name)

    class Meta(object):
        verbose_name = _('sale manager')
        verbose_name_plural = _('sale managers')


class Adviser(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    type = models.IntegerField(choices=ADVISER_TYPE_ENUM,
                               help_text="Account type", default=1)
    name = models.CharField(max_length=250,
                            help_text="Company name or adviser first name", unique=True)
    short_description = models.CharField(max_length=300,
                                         help_text="Short description displayed in sidebar")

    is_published = models.BooleanField(default=False)

    slug = AutoSlugField(_('slug'), max_length=50, unique=True, populate_from=('name',))

    telegram = models.CharField(max_length=255, null=True, blank=True)
    linkedin = models.URLField(max_length=255, null=True, blank=True)
    twitter = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    website = models.URLField(max_length=255, null=True, blank=True)

    member_since = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='images/advisers/', default='img/pics/default-avatar.svg')

    long_description = models.CharField(max_length=700, null=True, blank=True,
                                        help_text="Company's benefits")
    trading_volume = models.CharField(max_length=255, null=True, blank=True,
                                      help_text="24h trading volume")
    rating = models.CharField(max_length=255, null=True, blank=True,
                              help_text="Rating CoinMarketCap")

    page_title = models.CharField(max_length=255, null=True, blank=True,
                              help_text="Title of the page", default="Ambassador Exrates Exchange")

    ambassador_type = models.CharField(max_length=255, null=True, blank=True,
                                  help_text="Type of ambassador/sales/company", default="Verified Ambassador")

    def __str__(self):
        return '{}--{}'.format(self.get_type_display(), self.name)

    class Meta(object):
        verbose_name = _('Ambassador')
        verbose_name_plural = _('Ambassadors')

    def get_absolute_url(self):
        return reverse("adviser-detail", kwargs={"type": self.get_type_display().lower(), "slug": self.slug})

class GeneralFields(models.Model):
    telegram_followers = models.CharField(max_length=100)
    twitter_followers = models.CharField(max_length=100)

    facebook_followers = models.CharField(max_length=100)

    trading_volumes = models.CharField(max_length=100)
    active_trades = models.CharField(max_length=100)
    fiat_currencies = models.CharField(max_length=100)
    trading_pairs = models.CharField(max_length=100)

    def __str__(self):
        return 'General fields'

    class Meta(object):
        verbose_name = _('general fields')
        verbose_name_plural = _('general fields')


class AdviserPipeDrive(models.Model):
    adviser_id = models.CharField(max_length=36)
    deal_id = models.IntegerField()
    workspace = models.CharField(max_length=255)


LISTING_CHOICES = (
    ("IEO", "I need to conduct IEO"),
    ("Listing", "I need to list a coin")
    )
class Deal(models.Model):
    request_type = models.CharField(choices=LISTING_CHOICES, max_length=7)
    name = models.CharField(max_length=255)
    telegram = models.CharField(max_length=255)
    email = models.EmailField()
    company_name = models.CharField(max_length=255)
    link_to_project = models.CharField(max_length=255)

class DealPipeDrive(models.Model):
    deal_model_id = models.IntegerField()
    deal_id = models.IntegerField()
    workspace = models.CharField(max_length=255)

adviser/views.py
# -*- coding: utf-8 -*-
import requests
from django.conf import settings
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import FormView, TemplateView, UpdateView

from adviser.forms import AdviserForm, AdviserProfileForm, ListingForm, REQUEST_CHOICES, SupportForm
from adviser.models import Adviser, Manager
from clients.pipedrive_client import PipedriveClient
from clients.zendesk_client import ZendeskClient


from functools import wraps

class SupportPageView(FormView):
    template_name = 'main/support-center.html'
    form_class = SupportForm
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(SupportPageView, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('files')

        if form.is_valid():
            cleaned_data = form.cleaned_data
            request_type = dict(REQUEST_CHOICES)[int(cleaned_data.get('request_type'))]
            email = cleaned_data.get('email')
            message = cleaned_data.get('message')

            ZendeskClient().create_issue(request_type, message, email, files)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form(self, form_class=None):
        return SupportForm(self.request.POST, self.request.FILES)

class DealPageView(FormView):
    template_name = 'main/form-listing.html'
    form_class = ListingForm
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(DealPageView, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AdviserFormView(FormView):
    template_name = 'adviser/advisor-form.html'
    form_class = AdviserForm
    success_url = '.'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AdviserUpdateProfileView(UpdateView):
    template_name = 'adviser/adviser_profile.html'
    form_class = AdviserProfileForm
    model = Adviser
    success_url = '.'

    def get_object(self, queryset=None):
        return self.model.objects.get(slug=self.kwargs['slug'])

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AdviserProfileView(TemplateView):
    template_name = 'adviser/advisor-page.html'
    form_class = AdviserProfileForm
    model = Adviser
    success_url = '.'

    def get_object(self, queryset=None):
        return self.model.objects.get(slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        slug = self.kwargs['slug']
        data = super().get_context_data(**kwargs)
        data['adviser'] = get_object_or_404(Adviser, slug=slug)
        data['username'] = None
        data['form'] = ListingForm
        return data


class FiatPageView(TemplateView):
    template_name = 'main/fiat.html'


class AboutUsPageView(FormView):
    template_name = 'main/about-us.html'

    form_class = ListingForm
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(AboutUsPageView, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            PipedriveClient().create_deal(form.cleaned_data, [settings.PIPEDRIVE_ME, settings.PIPEDRIVE])
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ClientCenterPageView(TemplateView):
    template_name = 'main/client-center.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['contacts'] = Manager.objects.all()
        return data


class PrivacyPolicyPageView(TemplateView):
    template_name = 'main/privacy-policy.html'


# class TermsPageView(TemplateView):
#     template_name = 'main/terms-of-use.html'


class BecomeAdviserPageView(TemplateView):
    template_name = 'adviser/become-advisor.html'


class AdviserDemoPageView(TemplateView):
    template_name = 'adviser/adviser_page.html'
    success_url = '.'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['form'] = ListingForm
        return data


class ChatPageView(TemplateView):
    template_name = 'main/support-chat.html'


class AdvisorProfileView(UpdateView):
    template_name = 'adviser/advisor-profile.html'

    form_class = AdviserProfileForm
    model = Adviser
    success_url = '.'

    def get_object(self, queryset=None):
        return self.model.objects.get(slug=self.kwargs['slug'])

    def form_valid(self, form):
        adviser = form.save(commit=False)
        adviser.avatar = form.decode_base64_file(self.request.POST.get("avatar"))
        adviser.save()
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return super().form_invalid(form)

templates/adviser/advisor-form.html
{% load i18n %}

{% load static %}
<html>
    <head>
        <title>Ambassadors | Exrates</title>
<meta name="description" content="Meet official representatives of Exrates exchange. And become one of them!" />
        <!-- Main Meta information-->
        {% include 'basic/_head.html' %}
    </head>
    <body>
        <div class="form-listing-wr a-form">
            <div class="top-part">
                <a href="https://exrates.me" class="logo">
                    <img src="{% static 'img/pics/logo-header.svg' %}" alt="">
                </a>
                <div class="description">
                    <p>{% blocktrans %}Cryptocurrency Exchange{% endblocktrans %}</p>
                </div>
            </div>
            <div class="form-part">
                <form action="{% url 'advisor-form' %}" class="list-form nomodal" enctype="multipart/form-data" method="POST">{% csrf_token %}
                    <!-- start default variant -->
                    <div class="left-part">
                        <div class="title">
                            <h3 class="variable-title">{% blocktrans %}Fill the form to become an Ambassador{% endblocktrans %}</h3>
                        </div>
                        <div class="inputs-wr">
                            <div class="wrap-input input-item popup__wrap-input">
                                <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field" autocomplete="new-password" type="text" name="name" id="id_name">
                                <label class="wrap-input__label" for="id_name">{% blocktrans %}Name{% endblocktrans %}*</label>
                                <label class="error" for="id_name"><span class="standart-text">{{ form.name.errors }}<</span></label>
                            </div>
                            <div class="wrap-input input-item popup__wrap-input">
                                <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field" autocomplete="new-password" type="text" name="telegram" id="id_telegram" data-name="tg">
                                <label class="wrap-input__label" for="id_telegram">Telegram*</label>
                                <label class="error" for="id_telegram"><span class="standart-text"></span></label>
                            </div>
                            <div class="wrap-input input-item popup__wrap-input">
                                <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field" autocomplete="new-password" type="text" name="email" id="id_email">
                                <label class="wrap-input__label" for="id_email">Email*</label>
                                <label class="error" for="id_email"><span class="standart-text"></span></label>
                            </div>
                            <div class="wrap-input input-item popup__wrap-input">
                                <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field" autocomplete="new-password" type="text" name="linkedin" id="id_linkedin" data-name="link">
                                <label class="wrap-input__label" for="id_linkedin">Linkedin*</label>
                                <label class="error" for="id_linkedin"><span class="standart-text"></span></label>
                            </div>

                        <div class="capcha-container">
                        {{ form.captcha }}

                        <div class="error" for="{{ form.captcha.id_for_label }}"><span class="standart-text"></span>
                        </div>
                    </div>
                        </div>
                         <div class="button-wr">
                    <button class="standart-btn" type="submit"><span>{% blocktrans %}Submit{% endblocktrans %}</span></button>
                </div>
                <div class="left-part success-mess">
                    <div class="top-part">
                        <div class="pic">
                            <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 80 80" fill="none">
                                <circle cx="40" cy="40" r="39" stroke="#94C2FF" stroke-width="2" />
                                <rect x="22" y="37.1924" width="3" height="20" rx="1.5" transform="rotate(-45 22 37.1924)" fill="#94C2FF" />
                                <rect x="55.2344" y="28" width="3" height="30" rx="1.5" transform="rotate(45 55.2344 28)" fill="#94C2FF" />
                            </svg>
                        </div>
                        <div class="message-txt">
                            <p>{% blocktrans %}Your application is accepted{% endblocktrans %}</p>
                        </div>
                    </div>
                    <div class="bottom-part">
                        <nav class="success-nav">
                            <ul class="success-nav-list">
                                <li class="success-nav-list-item">
                                    <a href="https://exrates.me/dashboard"><span>{% blocktrans %}Trade{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="{%  url 'support-center'%}"><span>{% blocktrans %}Support{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="https://exrates.me/ieo"><span>{% blocktrans %}Token Sale{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="{% url 'client-center' %}"><span>{% blocktrans %}Contacts{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="{% url 'fiat'%}"><span>{% blocktrans %}Fiat{% endblocktrans %}</span></a>
                                </li>
                                <!--<li class="success-nav-list-item">
                                    <a href="#"><span>{% blocktrans %}Announcements{% endblocktrans %}</span></a>
                                </li>-->
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="right-part">
                <div class="title-wr">
                    <h4>{% blocktrans %}Benefits for Exrates Ambassadors{% endblocktrans %}</h4>
                </div>
                <div class="a-info-part">
                    <ul class="a-form-list">
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form1.svg'%}" alt="">
                            </div>
                            <span>{% blocktrans %}Special reward system for ambassadors: <br>get from 5% to 15%{% endblocktrans %}</span>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form2.svg'%}" alt="">
                            </div>
                            <span>{% blocktrans %}Get exclusive analytical market reports{% endblocktrans %}</span>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form3.svg'%}" alt="">
                            </div>
                            <span>{% blocktrans %}Participation in online trainings & webinars{% endblocktrans %}</span>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form4.svg'%}" alt="">
                            </div>
                            <span>{% blocktrans %}Your personal page on Exchange website{% endblocktrans %}</span>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form5.svg'%}" alt="">
                            </div>
                            <span>{% blocktrans %}Your personal manager{% endblocktrans %}</span>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form6.svg' %}" alt="">
                            </div>
                            <span>{% blocktrans %}Attend conferences & events as a part of Exrates team{% endblocktrans %}</span>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form7.svg'%}" alt="">
                            </div>
                            <span>{% blocktrans %}An opportunity to become a part of international community{% endblocktrans %}</span>
                        </li>
                        <li>
                            <div class="icon">
                                <img src="{% static 'img/pics/a-form8.svg'%}" alt="">
                            </div>
                            <span>{% blocktrans %}Referral program{% endblocktrans %}</span>
                        </li>
                    </ul>
                </div>
                <div class="back-btn">
                    <a href="#" onclick="window.history.back()"><span>
                            < {% blocktrans %}Back{% endblocktrans %}</span> </a> </div> </div> </form> </div>
        </div>
        {% include 'basic/_scripts.html' %}

    </body>



</html>