api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from api.views import CreateCurrencyReportView

urlpatterns = [

    url(r'^cryptocurrency/$', CreateCurrencyReportView.as_view(), name='currency'),

    ]

exrates_adviser/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import include, reverse
from django.utils.translation import activate

from adviser.views import (AboutUsPageView, AdviserDemoPageView, AdviserFormView, AdviserProfileView,
                           AdviserUpdateProfileView, AdvisorProfileView, BecomeAdviserPageView, ChatPageView,
                           ClientCenterPageView,
                           DealPageView, FiatPageView, PrivacyPolicyPageView, SupportPageView)#, TermsPageView)
from analytics.views import ArticlePageView, ArticlesListPageView, ListArticleView

activate('en')

from django.conf import settings
from django.contrib import messages

import requests


def check_recaptcha(function):
    def wrap(request, *args, **kwargs):
        request.recaptcha_is_valid = None
        if request.method == 'POST':
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
                }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            if result['success']:
                request.recaptcha_is_valid = True
            else:
                request.recaptcha_is_valid = False
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
        return function(request, *args, **kwargs)

    wrap.__doc__ = function.__doc__
    wrap.__name__ = function.__name__
    return wrap


def home(request):
    return redirect(reverse("about-us"))


def page_not_found_view(request):
    return render(request, '404.html', {})


urlpatterns = i18n_patterns(
        url(r'^$', home, name='home'),
        url(r'^analytics-detail/(?P<slug>[-\w]+)/$', ArticlePageView.as_view(), name='analytics-detail'),
        url(r'^form-listing/$', check_recaptcha(DealPageView.as_view()), name='deal'),
        url(r'^advisor-demo/$', check_recaptcha(AdviserDemoPageView.as_view()), name='adviser-demo'),

        url(r'^(?P<type>[-\w]+)-profile/(?P<slug>[-\w]+)/$', AdvisorProfileView.as_view(), name='advisor-profile'),

        url(r'^(?P<type>[-\w]+)/(?P<slug>[-\w]+)/update/$', check_recaptcha(AdviserUpdateProfileView.as_view()),
            name='adviser-update'),
        url(r'^(?P<type>[-\w]+)/(?P<slug>[-\w]+)/$', check_recaptcha(AdviserProfileView.as_view()), name='adviser-detail'),

        url(r'^fiat/$', FiatPageView.as_view(), name='fiat'),
        url(r'^client-center/$', ClientCenterPageView.as_view(), name='client-center'),
        url(r'^privacy-policy/$', PrivacyPolicyPageView.as_view(), name='privacy-policy'),
        # url(r'^terms-of-use/$', TermsPageView.as_view(), name='terms-of-use'),

        url(r'^become-ambassador/$', BecomeAdviserPageView.as_view(), name='become-advisor'),
        url(r'^about-us/$', check_recaptcha(AboutUsPageView.as_view()), name='about-us'),

        url(r'^ambassador-form/$', AdviserFormView.as_view(), name='advisor-form'),
        url(r'^support-center/$', check_recaptcha(SupportPageView.as_view()), name='support-center'),

        url(r'^chat/$', ChatPageView.as_view(), name='chat'),
        url(r'^analytics/$', ArticlesListPageView.as_view(), name='analytics-list'),



        ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls = [url('admin/', admin.site.urls),
url(r'^api/articles/$', ListArticleView.as_view(), name='articles-list1'),
        url('i18n/', include('django.conf.urls.i18n')),
        url(r'^ckeditor/', include('ckeditor_uploader.urls')),
        url(r'^api/', include('api.urls')),
        ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += urls

adviser/forms.py
# -*- coding: utf-8 -*-
from datetime import datetime

from captcha.fields import ReCaptchaField
from django import forms
from django.conf import settings
from django.forms import ModelForm, model_to_dict
from django.urls import reverse
from django.utils.text import slugify

from adviser.models import Adviser, AdviserPipeDrive, Deal, DealPipeDrive, LISTING_CHOICES
from clients.pipedrive_client import PipedriveClient

REQUEST_CHOICES = (
    (1, "Funds Withdrawal"),
    (2, "API Issue"),
    (3, "Improvement"),
    (4, "Deposit"),
    (5, "I see issue"),

    (6, "Help with my account"),
    (7, "Trading"),
    (8, "Promotion"),
    (9, "Security"),
    (10, "Business communication"),
    (11, "Application Performance"),
    (12, "Authentication"),
    (13, "Usability"),
    (14, "Other")

    )

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip
class SupportForm(forms.Form):
    request_type = forms.ChoiceField(choices=REQUEST_CHOICES)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea, max_length=700)
    files = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    captcha = ReCaptchaField(required=True)

    def __init__(self, *args, **kwargs):
        super(SupportForm, self).__init__(*args, **kwargs)
        for captcha in self.visible_fields():
            captcha.field.widget.attrs['data-callback'] = 'validateCapcha'


class ListingFormAdmin(ModelForm):
    request_type = forms.ChoiceField(choices=LISTING_CHOICES, widget=forms.RadioSelect)
    name = forms.CharField(max_length=255)
    telegram = forms.CharField(max_length=255, required=False)
    email = forms.EmailField()
    company_name = forms.CharField(max_length=255)
    link_to_project = forms.CharField(max_length=255, required=True)

    class Meta:
        model = Deal
        fields = ['request_type', 'name', 'telegram', 'email', 'company_name', 'link_to_project']

    def save(self, commit=True):

        instance = super(ListingFormAdmin, self).save(commit=False)
        if instance:
            model = instance
        else:
            model = self
        deals = PipedriveClient().create_deal(model_to_dict(model), [settings.PIPEDRIVE_ME, settings.PIPEDRIVE])

        if commit:
            instance.save()
        for deal in deals:
            adviser_pipedrive = DealPipeDrive(deal_id=deal["deal_id"], deal_model_id=instance.id,
                                              workspace=deal["workspace"])
            adviser_pipedrive.save()
        return instance

class ListingForm(ListingFormAdmin):
    captcha = ReCaptchaField()

    def __init__(self, *args, **kwargs):
        super(ListingForm, self).__init__(*args, **kwargs)
        for captcha in self.visible_fields():
            captcha.field.widget.attrs['data-callback'] = 'validateCapcha'



class AdviserForm(ModelForm):
    name = forms.CharField(max_length=255)
    telegram = forms.CharField(max_length=255)
    email = forms.EmailField()
    linkedin = forms.CharField()
    captcha = ReCaptchaField(required=True)

    class Meta:
        model = Adviser
        fields = ['name', 'telegram', 'email', 'linkedin']


    def __init__(self, *args, **kwargs):
        super(AdviserForm, self).__init__(*args, **kwargs)
        for captcha in self.visible_fields():
            captcha.field.widget.attrs['data-callback'] = 'validateCapcha'

    def save(self, commit=True):

        instance = super(AdviserForm, self).save(commit=False)
        instance.type = 1
        if instance:
            model = instance
        else:
            model = self
        edit_url = "{}{}".format(settings.SITE, reverse('adviser-update', kwargs={"type": model.get_type_display().lower(), "slug": slugify(model.name)}))
        update_url = "{}{}".format(settings.SITE, reverse('adviser-detail', kwargs={"type": model.get_type_display().lower(), "slug": slugify(model.name)}))
        deals = PipedriveClient().create_or_update_adviser(model_to_dict(instance), edit_url, update_url, [settings.PIPEDRIVE_ME, settings.PIPEDRIVE])

        if commit:
            instance.save()
        for deal in deals:
            adviser_pipedrive = AdviserPipeDrive(deal_id=deal["deal_id"], adviser_id=instance.id, workspace=deal["workspace"])
            adviser_pipedrive.save()
        return instance




class AdviserProfileForm(ModelForm):
    email = forms.EmailField()
    captcha = ReCaptchaField(required=True)

    class Meta:
        model = Adviser
        fields = ['name',  'short_description', 'email', 'telegram', 'linkedin', 'avatar', ]

    def __init__(self, *args, **kwargs):
        super(AdviserProfileForm, self).__init__(*args, **kwargs)
        for captcha in self.visible_fields():
            captcha.field.widget.attrs['data-callback'] = 'validateCapcha'

    def save(self, commit=True):
        instance = super(AdviserProfileForm, self).save(commit=False)
        instance.member_since = datetime.today()

        if instance:
            model = instance
        else:
            model = self
        edit_url = "{}{}".format(settings.SITE, reverse('adviser-update', kwargs={"type": model.get_type_display().lower(),"slug": slugify(model.name)}))
        update_url = "{}{}".format(settings.SITE, reverse('adviser-detail', kwargs={"type": model.get_type_display().lower(),"slug": slugify(model.name)}))
        deals = PipedriveClient().create_or_update_adviser(model_to_dict(model), edit_url, update_url,
                                                           [settings.PIPEDRIVE_ME, settings.PIPEDRIVE])
        if commit:
            model.save()
        for deal in deals:
            adviser_pipedrive = AdviserPipeDrive(deal_id=deal["deal_id"], adviser_id=model.id,
                                                 workspace=deal["workspace"])
            adviser_pipedrive.save()
        return model

    def decode_base64_file(self, data):

        def get_file_extension(file_name, decoded_file):
            import imghdr

            extension = imghdr.what(file_name, decoded_file)
            extension = "jpg" if extension == "jpeg" else extension

            return extension

        from django.core.files.base import ContentFile
        import base64
        import six
        import uuid

        # Check if this is a base64 string
        if isinstance(data, six.string_types):
            # Check if the base64 string is in the "data:" format
            if 'data:' in data and ';base64,' in data:
                # Break out the header from the base64 content
                header, data = data.split(';base64,')

            # Try to decode the file. Return validation error if it fails.
            try:
                decoded_file = base64.b64decode(data)
            except TypeError:
                TypeError('invalid_image')

            # Generate file name:
            file_name = str(uuid.uuid4())[:12]  # 12 characters are more than enough.
            # Get the file name extension:
            file_extension = get_file_extension(file_name, decoded_file)

            complete_file_name = "%s.%s" % (file_name, file_extension,)

            return ContentFile(decoded_file, name=complete_file_name)


class AdviserAdminForm(ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Adviser
        fields = ['name', 'short_description', 'email', 'telegram', 'linkedin', 'avatar', ]

    def save(self, commit=True):
        instance = super(AdviserAdminForm, self).save(commit=False)
        if instance:
            model = instance
        else:
            model = self
        edit_url = "{}{}".format(settings.SITE, reverse('adviser-update', kwargs={"type": model.get_type_display().lower(),"slug": slugify(model.name)}))
        update_url = "{}{}".format(settings.SITE, reverse('adviser-detail', kwargs={"type": model.get_type_display(

                ).lower(),"slug": slugify(model.name)}))
        deals = PipedriveClient().create_or_update_adviser(model_to_dict(model), edit_url, update_url,
                                                           [settings.PIPEDRIVE_ME, settings.PIPEDRIVE])
        if commit:
            model.save()
        for deal in deals:
            adviser_pipedrive = AdviserPipeDrive(deal_id=deal["deal_id"], adviser_id=model.id,
                                                 workspace=deal["workspace"])
            adviser_pipedrive.save()
        return model

templates/main/article.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{%  block title %}
<head  prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#">
   <meta name="description" content="Some description.">
   <title>Websitename</title>
   <meta property="og:title" content="Websitename">
   <meta property="og:url" content="https://www.somewebsite.com/">
   <meta property="og:description" content="The easiest way of making digital music.">
   <meta property="og:image" content="https://www.judgemysound.com/static/image.png">
</head>
{% endblock %}
{% load i18n %}
p {
  color: white;
}
{% block content %}
    <div id="fb-root"></div>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3&appId=1867139203553457&autoLogAppEvents=1"></script>
    {{ article.name }}

    <hr>
     <hr>
     <hr>
     {% language 'en' %}
    {{ article.published_at|date:"M/d/Y G:i A l" }}
    {% endlanguage %}
     <hr>
     <hr>
     <hr>
     <hr>
     <hr>

    {{ article.article|safe }}
     <hr>
     <hr>
       <a href="http://www.facebook.com/sharer.php?u=h{{ request.get_full_path }}" target="_blank">
        <img src="https://simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" />
    </a>

    <!-- Twitter -->
    <a href="https://twitter.com/share?url={{request.get_full_path }}&amp;text=Simple%20Share%20Buttons&amp;hashtags=simplesharebuttons" target="_blank">
        <img src="https://simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" />
    </a>

    <hr>

    <div class="share-btns">
                        <a class="standart-btn reverse" href="javascript:window.open('https://twitter.com/intent/tweet/?url='+encodeURIComponent(window.location.href), '_blank')"><span>Share in</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="17" height="14" viewBox="0 0 17 14" fill="none">
                                <path d="M17 1.65738C16.3678 1.93846 15.6942 2.12477 14.9919 2.21523C15.7144 1.778 16.2658 1.09092 16.5251 0.262769C15.8514 0.669846 15.1077 0.957385 14.3151 1.11785C13.6754 0.427539 12.7638 0 11.7693 0C9.83981 0 8.28644 1.58738 8.28644 3.53339C8.28644 3.81339 8.30981 4.08262 8.36719 4.33892C5.46975 4.19569 2.90594 2.78815 1.18362 0.644C0.882937 1.17277 0.706563 1.778 0.706563 2.42954C0.706563 3.65292 1.32812 4.73738 2.25463 5.36523C1.69469 5.35446 1.14538 5.18969 0.68 4.93015C0.68 4.94092 0.68 4.95492 0.68 4.96892C0.68 6.68554 1.88806 8.11139 3.47225 8.43985C3.18856 8.51846 2.87937 8.55615 2.5585 8.55615C2.33538 8.55615 2.11012 8.54323 1.89869 8.49585C2.35025 9.89477 3.63163 10.9232 5.15525 10.9566C3.9695 11.8968 2.46394 12.4632 0.834063 12.4632C0.54825 12.4632 0.274125 12.4503 0 12.4148C1.54381 13.4238 3.37344 14 5.3465 14C11.7597 14 15.266 8.61539 15.266 3.948C15.266 3.79185 15.2607 3.64108 15.2533 3.49138C15.9449 2.99385 16.5261 2.37246 17 1.65738Z" fill="#AAB1C4"></path>
                            </svg>
                        </a>
                        <a class="standart-btn reverse" href="javascript:window.open('https://telegram.me/share/url?url='+encodeURIComponent(window.location.href), '_blank')" rel="noopener" aria-label="Share on Telegram"><span>Share in</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="17" height="14" viewBox="0 0 17 14" fill="none">
                                <path d="M0.284014 6.71295L3.98908 8.0958L5.42317 12.7078C5.51493 13.0032 5.87614 13.1124 6.11588 12.9164L8.18115 11.2327C8.39764 11.0563 8.70599 11.0475 8.93223 11.2118L12.6572 13.9162C12.9137 14.1026 13.2771 13.9621 13.3414 13.6522L16.0701 0.526311C16.1404 0.187781 15.8077 -0.0946306 15.4854 0.0300402L0.279672 5.89594C-0.0955728 6.04066 -0.0923033 6.57193 0.284014 6.71295ZM5.19206 7.35967L12.4331 2.89988C12.5633 2.81996 12.6972 2.99593 12.5854 3.09959L6.60942 8.65456C6.39937 8.85009 6.26387 9.11176 6.22549 9.39578L6.02192 10.9044C5.99496 11.1058 5.71202 11.1258 5.65643 10.9309L4.87352 8.17989C4.78385 7.86613 4.91452 7.53097 5.19206 7.35967Z" fill="#AAB1C4"></path>
                            </svg>
                        </a>
                        <a class="standart-btn reverse" href="javascript:window.open('https://facebook.com/sharer/sharer.php?u='+encodeURIComponent(window.location.href), '_blank')" rel="noopener" aria-label="Share on Facebook"><span>Share in</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="8" height="14" viewBox="0 0 8 14" fill="none">
                                <path d="M7.49934 0.00291293L5.68387 0C3.64426 0 2.32617 1.35233 2.32617 3.44542V5.03399H0.500797C0.343063 5.03399 0.215332 5.16187 0.215332 5.3196V7.62126C0.215332 7.77899 0.343209 7.90672 0.500797 7.90672H2.32617V13.7145C2.32617 13.8723 2.4539 14 2.61163 14H4.99322C5.15096 14 5.27869 13.8721 5.27869 13.7145V7.90672H7.41298C7.57071 7.90672 7.69844 7.77899 7.69844 7.62126L7.69931 5.3196C7.69931 5.24386 7.66917 5.17133 7.61571 5.11773C7.56226 5.06414 7.48944 5.03399 7.4137 5.03399H5.27869V3.68734C5.27869 3.04008 5.43293 2.71151 6.27607 2.71151L7.49905 2.71107C7.65664 2.71107 7.78437 2.58319 7.78437 2.4256V0.288381C7.78437 0.130936 7.65679 0.00320423 7.49934 0.00291293Z" fill="#AAB1C4"></path>
                            </svg>
                        </a>
                    </div>

<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-width="200" data-numposts="5"></div>
 <hr>

{% endblock %}

templates/main/articles_list.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{%  block title %}
{% endblock %}
{% load i18n %}

p {
  color: white;
}
{% block content %}
    <div id="fb-root"></div>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3&appId=1867139203553457&autoLogAppEvents=1"></script>
    {% for article in articles %}

        <a href ={% url 'article-detail' slug=article.slug %}>{{ article.name }}</a>

    <hr>
     <hr>
     <hr>
     {% language 'en' %}
    {{ article.published_at|date:"M/d/Y G:i A l" }}
    {% endlanguage %}
     <hr>
     <hr>
     <hr>

    {{ article.short_description }}

    {% endfor %}
     <hr>
     <hr>
 <hr>

{% endblock %}

templates/main/become_adviser.html
{% extends 'base.html' %}


{% block body %}

    <form action="{% url 'deal' %}" enctype="multipart/form-data" method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>

{% endblock %}

templates/main/form-listing.html
{% load static urls %}
{% load i18n %}
<html>
<head>
    <title>Apply for listing | Exrates</title>
    <meta name="description"
          content="Apply your coin for listing in 2 clicks! Receive your exclusive offer immediately and get listed in few days!"/>
    <!-- Main Meta information-->
    {% include 'basic/_head.html' %}
</head>
<body>
{% get_extra_fields as extra_fields %}
<div class="form-listing-wr">
    <div class="top-part">
        <a href="https://exrates.me" class="logo">
            <img src="{% static 'img/pics/logo-header.svg' %}" alt="">
        </a>
        <div class="description">
            <p>Cryptocurrency Exchange</p>
        </div>
    </div>
    <div class="form-part">
        <form action="{% url 'deal' %}" class="list-form nomodal" enctype="multipart/form-data"
              method="POST"> {% csrf_token %}
            <!-- start default variant -->
            <div class="left-part">
                <div class="title">
                    <h3 class="variable-title">{% blocktrans %}Apply to conduct an IEO{% endblocktrans %}</h3>
                </div>
                <div class="radio-wr">
                    <div class="radio-item">
                        <input class="accessibility-content radio-form-list" type="radio" name="request_type"
                               id="id_request_type_0" value="IEO" data-head="{% trans 'Apply to conduct an IEO' %}"
                                {% if '=ieo' in request.build_absolute_uri or "type" not in request.build_absolute_uri %}
                               checked="checked" {% endif %}>
                        <label class="check" for="id_request_type_0"></label>
                        <label class="check-txt" for="id_request_type_0"><span>{% blocktrans %}I need to conduct an
                            IEO{% endblocktrans %}</span></label>
                    </div>
                    <div class="radio-item">
                        <input class="accessibility-content radio-form-list" type="radio" name="request_type"
                               id="id_request_type_1" value="Listing" data-head="{% trans 'Apply for Listing' %}"
                                {% if '=listing' in request.build_absolute_uri %} checked="checked" {% endif %}>
                        <label class="check" for="id_request_type_1"></label>
                        <label class="check-txt" for="id_request_type_1"><span>{% blocktrans %}I need to list a
                            coin{% endblocktrans %}</span></label>
                    </div>
                </div>
                <div class="inputs-wr">
                    <div class="wrap-input input-item popup__wrap-input">
                        <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field"
                               autocomplete="new-password" type="text" name="name" id="id_name">
                        <label class="wrap-input__label" for="id_name">{% blocktrans %}Name{% endblocktrans %}*</label>
                        <label class="error" for="id_name"><span class="standart-text"></span></label>
                    </div>
                    <div class="wrap-input input-item popup__wrap-input">
                        <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field"
                               autocomplete="new-password" type="text" name="telegram" id="id_telegram" data-name="tg">
                        <label class="wrap-input__label" for="id_telegram">{% blocktrans %}Telegram{% endblocktrans %}
                            *</label>
                        <label class="error" for="id_telegram"><span class="standart-text"></span></label>
                    </div>
                    <div class="wrap-input input-item popup__wrap-input">
                        <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input required-field reqiered-field"
                               autocomplete="new-password" type="text" name="email" id="id_email">
                        <label class="wrap-input__label" for="id_email">{% blocktrans %}Email{% endblocktrans %}
                            *</label>
                        <label class="error" for="id_email"><span class="standart-text"></span></label>
                    </div>
                    <div class="wrap-input input-item popup__wrap-input">
                        <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field"
                               autocomplete="new-password" type="text" name="company_name" id="id_company_name">
                        <label class="wrap-input__label" for="id_company_name">{% blocktrans %}Company
                            name{% endblocktrans %}*</label>
                        <label class="error" for="id_company_name"><span class="standart-text"></span></label>
                    </div>
                    <div class="wrap-input input-item popup__wrap-input">
                        <input class="wrap-input__input ng-dirty ng-valid ng-touched form-input reqiered-field"
                               autocomplete="new-password" type="text" name="link_to_project" id="id_link_to_project"
                               data-name="link">
                        <label class="wrap-input__label" for="id_link_to_project">{% blocktrans %}Link to the
                            website{% endblocktrans %}*</label>
                        <label class="error" for="id_link_to_project"><span class="standart-text"></span></label>
                    </div>

                    <div class="capcha-container">
                        {{ form.captcha }}

                        <div class="error" for="{{ form.captcha.id_for_label }}"><span class="standart-text"></span>
                        </div>
                    </div>
                </div>

                <div class="button-wr">
                    <button class="standart-btn" type="submit"><span>{% blocktrans %}Submit{% endblocktrans %}</span>
                    </button>
                </div>

                <div class="left-part success-mess">
                    <div class="top-part">
                        <div class="pic">
                            <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 80 80"
                                 fill="none">
                                <circle cx="40" cy="40" r="39" stroke="#94C2FF" stroke-width="2"/>
                                <rect x="22" y="37.1924" width="3" height="20" rx="1.5"
                                      transform="rotate(-45 22 37.1924)" fill="#94C2FF"/>
                                <rect x="55.2344" y="28" width="3" height="30" rx="1.5"
                                      transform="rotate(45 55.2344 28)" fill="#94C2FF"/>
                            </svg>
                        </div>
                        <div class="message-txt">
                            <p>{% blocktrans %}Your application is accepted{% endblocktrans %}</p>
                        </div>
                    </div>
                    <div class="bottom-part">
                        <nav class="success-nav">
                            <ul class="success-nav-list">
                                <li class="success-nav-list-item">
                                    <a href="https://exrates.me/dashboard"><span>{% blocktrans %}
                                        Trade{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="{% url 'support-center' %}"><span>{% blocktrans %}
                                        Support{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="https://exrates.me/dashboard"><span>{% blocktrans %}Token
                                        Sale{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="{% url 'client-center' %}"><span>{% blocktrans %}
                                        Contacts{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="{% url 'fiat' %}"><span>{% blocktrans %}Fiat{% endblocktrans %}</span></a>
                                </li>
                                <li class="success-nav-list-item">
                                    <a href="https://support.exrates.me/categories/announcements"><span>{% blocktrans %}
                                        Announcements{% endblocktrans %}</span></a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

            <div class="right-part">
                <div class="partner-part">
                    <div class="coinmarketcup partner-item">
                        <div class="pic">
                            <img src="{% static 'img/pics/coinmarketcup.svg' %}" alt="">
                        </div>
                        <div class="description-right">
                            <p><span>TOP-50</span> {% blocktrans %}by CoinMarketCap{% endblocktrans %}</p>
                        </div>
                    </div>
                    <div class="coingecko partner-item">
                        <div class="pic">
                            <img src="{% static 'img/pics/coingecko.svg' %}" alt="">
                        </div>
                        <div class="description-right">
                            <p>{% blocktrans %}Ranked by CoinGecko{% endblocktrans %}</p>
                        </div>
                    </div>
                </div>
                <div class="info-part">
                    <ul class="form-list">
                        <li><span>{% blocktrans %}Supporting all types of coins{% endblocktrans %}</span></li>
                        <li><span class="weight">24/7 </span><span>{% blocktrans %}Online
                            Support{% endblocktrans %}</span></li>
                        
                        <li><span class="weight">{{ extra_fields.active_trades }} </span><span>{% blocktrans %}active
                            traders{% endblocktrans %}</span></li>
                        <li><span class="weight">X-Platform </span><span>{% blocktrans %}for
                            IEO{% endblocktrans %}</span>
                            <span class="label">{% blocktrans %}NEW{% endblocktrans %}</span></li>
                       
                        <li><span class="weight">{% blocktrans %} {% endblocktrans %}</span><span>{% blocktrans %}Trading API for AlgoTraders{% endblocktrans %}</span></li>
                    </ul>
                </div>
                <div class="back-btn">
                    <a href="#" onclick="window.history.back()"><span>
                                    &lt; {% blocktrans %}Back{% endblocktrans %}</span> </a></div>
            </div>
        </form>
    </div>
</div>

{% include 'basic/_scripts.html' %}
</body>
</html>